name:                gw-treasure
version:             0.1.0.0
github:              "wgaffa/gw-treasure"
license:             BSD3
author:              "Patrik Maunus"
maintainer:          "subscription@skriptladan.se"
copyright:           "Patrik Maunus 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wgaffa/gw-treasure#readme>

dependencies:
- base >= 4.7 && < 5
- time
- text
- cassava

library:
  source-dirs: src

executables:
  gw-treasure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gw-treasure

tests:
  gw-treasure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gw-treasure
